---
title: "SQL and RStudio Connection"
author: "Yihun Zeleke"
date: "10/15/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```
**Steps to connect MySql with Rstudio**   
- Install `odbc` package.
- Go to my connection rstudion panel and then create a new connection with `MySQL ODBC 8.0 Unicode Driver`.

```{r}
library(DBI)
con <- dbConnect(odbc::odbc(), .connection_string = "Driver={MySQL ODBC 8.0 Unicode Driver};",
                 #timeout = 10,
                 server = "localhost",
                 Database = "gapminder", # schema we created in the mysql-workbench
                 UID = "root", PWD = "pass1269natanya", # password for mysql-workbench
                 Port = 3306)
```

Now we are making a connection with mysql-workbench. Let's push some data to server.

```{r}
library(tidyverse)
library(gapminder)
data("gapminder")

my_tbl <- Id(schema = "gapminder", table = "gapminder_table")
dbWriteTable(con, my_tbl, gapminder)
```

Read data from the database
```{r}
gapminder_db <- tbl(con, "gapminder_table") # with connection and table in the database

```

Now we have connection with server and we can apply dplyr functions along with.
```{r}
gapminder_db %>% 
  group_by(continent) %>% 
  summarise(avg_continent = mean(gdpPercap))
```










































